---
driver:
  name: vagrant
  customize:
    nictype1: virtio

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-15.04

suites:
  - name: default
    run_list:
      - recipe[docker-registry2-docker]
    attributes:
      docker:
        version: 1.8.1
